CREATE TABLE LOKALIZACJA
(
ID_LOKALIZACJI NUMBER(9,0) PRIMARY KEY,
ULICA VARCHAR2(32) NOT NULL,
NUMER_DZIALKI NUMBER(4,0) NOT NULL,
MIEJSCOWOSC VARCHAR2(32) NOT NULL,
PANSTWO VARCHAR2(32) NOT NULL
);

CREATE TABLE PASTWISKA
(
ID_PASTWISKA NUMBER(9,0) PRIMARY KEY,
POJEMNOSC NUMBER(6,0) NOT NULL,
ID_LOKALIZACJI NUMBER(4,0) REFERENCES LOKALIZACJA(ID_LOKALIZACJI) NOT NULL
);

CREATE TABLE PRACOWNICY
(
ID_PRACOWNIKA NUMBER(9,0) PRIMARY KEY,
IMIE VARCHAR2(16) NOT NULL,
NAZWISKO VARCHAR2(32) NOT NULL,
NUMER_TEL NUMBER(13,0) CHECK(LENGTH(NUMER_TEL) >= 9) NOT NULL,
ID_KIEROWNIKA NUMBER(9,0) REFERENCES PRACOWNICY(ID_PRACOWNIKA)
);

CREATE TABLE OBORY
(
ID_OBORY NUMBER(9,0) PRIMARY KEY,
POJEMNOSC NUMBER(6,0) NOT NULL,
ID_KIEROWNIKA NUMBER(9,0) REFERENCES PRACOWNICY(ID_PRACOWNIKA) NOT NULL,
ID_PASTWISKA NUMBER(9,0) REFERENCES PASTWISKA(ID_PASTWISKA) NOT NULL,
ID_LOKALIZACJI NUMBER(9,0) REFERENCES LOKALIZACJA(ID_LOKALIZACJI) NOT NULL
);

CREATE TABLE RASY
(
ID_RASY NUMBER(9,0) PRIMARY KEY,
NAZWA VARCHAR2(32) NOT NULL,
SREDNIA_WYDAJNOSC NUMBER(5,0),
SREDNIA_WAGA NUMBER(4,0),
SREDNIA_DL_ZYCIA NUMBER(3,1)
);

CREATE TABLE KROWY
(
ID_KROWY NUMBER(9,0) PRIMARY KEY,
WYDAJNOSC_MLECZNA NUMBER(5,0) NOT NULL,
DATA_UR DATE NOT NULL,
ID_RASY NUMBER(9,0) REFERENCES RASY(ID_RASY) NOT NULL,
ID_OBORY NUMBER(9,0) REFERENCES OBORY(ID_OBORY) NOT NULL
);

